---
- name: install default packages
  yum:
    name: "{{ item }}"
    state: "present"
  loop:
    - vim
    - java-17-openjdk

- name: provide hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: '0644'

- name: stop filewall
  systemd:
    name: firewalld
    state: stopped
    enabled: no