---
- name: install default packages
  yum:
    name: "{{ item }}"
    state: "present"
  loop:
    - vim

- name: provide hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: '0644'
