version: '3.9'
services:
  jenkins:
    build: ./jenkinsCasC
    restart: always
    volumes:
      - ./data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=https://raw.githubusercontent.com/hexqueller/IPR/master/jenkins-minimal-example.yaml
    user: root
