version: '3.9'
services:

  jenkins:
    build: ./jenkinsCasC
    restart: always
    volumes:
      - ./data:/var/jenkins_home:rw
    ports:
      - "8080:8080"
    environment:
      - CASC_JENKINS_CONFIG=/user/local/jenkins-config.yaml
      - TZ=Europe/Moscow
    depends_on:
      - docker-ssh-agent

  docker-ssh-agent:
    build: ./ssh-agent
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClDjCi8cbTwwPF109h5WpjrPT8DyuB1D2PG/DpDazRYiBnX0G57vBkJUiQj3hR6VrOJHPuQjUcULyXFr6ONkUzzMs14FBelFLJCzXEUV6oLutvbabvSpTfZIHQjw3n/7BdDpRRMRnFonbmZSTGEvm9XprHf4MNDzdo7iuCFu6462BEqVqAfE/nEu+k++oKZz4PTQGSPsIwWoLDzCQ7ilzs+UWj37kX+GQCk0msoDyOqhlhQuBnyAWnOW9Vd8zW0WUKiBZO0al9VfXNNx9iVWsdAgnlVovqvz22RhuPZSA92IeyMTGrShdzrSLnw+m3Xgz1kha5w3nlPP6NO4MvL/I7
  
  tomcat:
    build: ./tomcat
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - jenkins

  vault:
    image: vault:1.13.3
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_LOCAL_CONFIG=/vault/config/config.hcl
    command: sh -c "vault server -config=/vault/config/config.hcl & sleep 5 && sh /vault/init.sh; tail -f /dev/null"
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - ./vault/init.sh:/vault/init.sh
    cap_add:
      - IPC_LOCK
    depends_on:
      - jenkins