credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "2198bf1d-245a-4152-9255-9b6508bd4bc4"
          privateKeySource:
            directEntry:
              privateKey: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEowIBAAKCAQEApQ4wovHG08MDxddPYeVqY6z0/A8rgdQ9jxvw6Q2s0WIgZ19B
                ue7wZCVIkI94UelaziRz7kI1HFC8lxa+jjZFM8zLNeBQXpRSyQs1xFFeqC7rb22m
                70qU32SB0I8N5/+wXQ6UUTEZxaJ25mUkxhL5vV6ax3+DDQ83aO4rghbuuOtgRKla
                gHxP5xLvpPvqCmc+D00Bkj7CMFqCw8wkO4pc7PlFo9+5F/hkApNJrKA8jqoZYULg
                Z8gFpzlvVXfM1tFlCogWTtGpfVX1zTcfYlVrHQIJ5VaL6r89tkYbj2UgPdiHsjEx
                q0oXc60i58Ppt14M9ZIWucN55Tz+jTuDLy/yOwIDAQABAoIBAF2ffOsQZY18kslH
                5hlLfltnodbP7AfKkdh5Kt+nCB4EoQjBuZBz/htwIocNOlyMFxvTBYdiOqoDCdZR
                6mjUU9CcG7BFupDLZWHwX+Epnp2bb6RW+FfHYEaOxiu82VB9clZ2jJ65UTsPeo4Z
                VRCddtd5sCX1KCriNLXqUveJdoOg5lEeDpjRbz530JxDXYp2R75ponQ20tdQMXxC
                Vl6oYRRj2/7gJ25OJh4O0PS9xNKqIx7/0pULAwq3F/fBKj30ZbSgdnrUqJPkkkRq
                lW8eWdzk0cZtJmJmstbCD8H684tqAZoYr3B0dxSDhA8ZGxKvLWeEU6UnLOj6vWiY
                1QMeM4ECgYEA0RIsLcHWjc62qRD+9EMj82p8+HsSbv07TQzzBFUIDl0PD9MB00aX
                /Zf7b2hqpxdeUUOTtLHUT7Kov6QjgBjgmQyE/yDmS7cOfyd04bHjW9GPKgtSSbyU
                OVim1FXD+hCSWIlX1F1HpROpKJv/9jnjGB9M5LEFK+WbcaAv8PYZhdsCgYEAyhrB
                YYfmOr92N3t1XZZQijOkxLHLaRIEotXMJWOXQe1Nt80Qe+1oW6T4hM6/Yup1tVll
                1QDaTIK3UKcWjh1wS+VJyznMNzhMaCpKhsjzBiQNlSpcwjfGMI2vGZS0tczE9VNk
                YRWfjzICZ1VGTFr9pf7D1K8TNxfHFFVjZ5wGYyECgYBKCHxaa6R1LLjj31/Y0Rme
                7Zt5ReN+J+/i1e4MH6wtoeheeyLPVNUneLURe1EhABZnAl4Ag2QiIKq+yfnEN4r4
                x0UlLto9/4GDp04tSZewAOIISmAGOl/meq0AzaoLF+kqrt/KFIn1O6QP/EXERDVV
                amgJJ2IkbDcCIm43jn31NwKBgQCtBV7MynV1kff4477Ekiz9Q90pbzS/DOffJ72P
                vMT/cdL5KZuVHNgcrQz9VapPWn3O9WvSgNpiaf3aFFGg9N7weqlETITiOVZgTuRi
                o6I6fZ8LNqsWsnz/kCx5b++NPHLZu7zRyJtDEgMwx7ZZJATGmWa5q/B9V+PdKoTh
                bJejQQKBgGr+oRBYtZgHBvubITHN26VvhBXO6uLF3JALwIZ9qwdcAZ4HPRguaxoP
                6a2Y4+JQKlQ+O1IaiPqrC5vynuVoypoCwvYp4c7BAx6YGyiXQuetj/j1BAeXBIi5
                F3GybP2Hdv48xCEBLWlJHzQWP/fke0OnUmZB8YLFq+Qx+LPqsGAz
                -----END RSA PRIVATE KEY-----
          scope: GLOBAL
          username: "jenkins"
      - vaultAppRoleCredential:
          description: "vault-jenkins-role"
          id: "vault-jenkins-role"
          path: "approle"
          roleId: "1aa708ed-623b-2b65-dd07-eb037749b395"
          scope: GLOBAL
          secretId: "2bfa21a5-0533-e777-93ae-dcbb3d275a07"
          usePolicies: false
      - vaultUsernamePasswordCredentialImpl:
          description: "vault-jenkins"
          engineVersion: 1
          id: "vault-jenkins"
          passwordKey: "password"
          path: "secrets/creds/jenkins"
          scope: GLOBAL
          usernameKey: "username"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.SecurityIsOffMonitor"
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  - name: "docker-agent01"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  nodes:
  - permanent:
      launcher:
        ssh:
          credentialsId: "2198bf1d-245a-4152-9255-9b6508bd4bc4"
          host: "docker-ssh-agent"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyTrustedKeyVerificationStrategy:
              requireInitialManualTrust: false
      name: "docker-agent01"
      numExecutors: 2
      remoteFS: "/home/jenkins"
      retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  systemMessage: "CasC enabled!"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
    theme: "darkSystem"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "default-lib"
      retriever:
        modernSCM:
          libraryPath: "./"
          scm:
            git:
              id: "4df5e90d-b0a0-4b32-9ffc-992c26149341"
              remote: "https://github.com/hexqueller/IPR.git"
              traits:
              - "gitBranchDiscovery"
  hashicorpVault:
    configuration:
      disableChildPoliciesOverride: false
      engineVersion: 1
      skipSslVerification: true
      timeout: 60
      vaultCredentialId: "vault-jenkins-role"
      vaultUrl: "http://vault:8200"
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    gradleCaptureTaskInputFiles: true
    injectCcudExtension: false
    injectMavenExtension: false
    mavenCaptureGoalInputFiles: true
  location:
    adminAddress: "адрес еще не настроен <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      multibranchPipelineJob('master-git') {
          branchSources {
              git {
                  id = 'master-git'
                  remote('https://github.com/hexqueller/IPR.git')
              }
          }
      }